### ISSUE TITLE
Mike Roadmap

### ISSUE THREAD

**Issue by michaecleyn** [michaecleyn/SimpleSocial#1]
- [x] make index home page
- [x] add devise
- [x] user sign up with omniauth twitter account
- [ ] take user handle and display tweets
- [ ] make user tweet out

**Comment by donburi** [comment]
Looks great!

**Comment by michaecleyn** [comment]
will do the second last points:

take handle to display tweets
make user tweet out

in another branch
